version: '3'
services:
  spark-master:
    hostname: spark-master
    image: ymslanda.innovationgarage.tech:5000/spark-master:${SPARK_MASTER_VERSION}
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      
  spark-worker-1:
    hostname: spark-worker-1
    image: bde2020/spark-worker:2.3.1-hadoop2.7
    depends_on:
      - spark-master
    ports:
      - "8181:8181"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      
  # spark-worker-2:
  #   image: bde2020/spark-worker:2.3.1-hadoop2.7
  #   container_name: spark-worker-2
  #   depends_on:
  #     - spark-master
  #   ports:
  #     - "8182:8182"
  #   environment:
  #     - "SPARK_MASTER=spark://spark-master:7077"
      
  # spark-worker-3:
  #   image: bde2020/spark-worker:2.3.1-hadoop2.7
  #   container_name: spark-worker-3
  #   depends_on:
  #     - spark-master
  #   ports:
  #     - "8183:8183"
  #   environment:
  #     - "SPARK_MASTER=spark://spark-master:7077"
      
  # spark-worker-4:
  #   image: bde2020/spark-worker:2.3.1-hadoop2.7
  #   container_name: spark-worker-4
  #   depends_on:
  #     - spark-master
  #   ports:
  #     - "8184:8184"
  #   environment:
  #     - "SPARK_MASTER=spark://spark-master:7077"
      
  # spark-worker-5:
  #   image: bde2020/spark-worker:2.3.1-hadoop2.7
  #   container_name: spark-worker-5
  #   depends_on:
  #     - spark-master
  #   ports:
  #     - "8185:8185"
  #   environment:
  #     - "SPARK_MASTER=spark://spark-master:7077"
      
  # spark-worker-6:
  #   image: bde2020/spark-worker:2.3.1-hadoop2.7
  #   container_name: spark-worker-6
  #   depends_on:
  #     - spark-master
  #   ports:
  #     - "8186:8186"
  #   environment:
  #     - "SPARK_MASTER=spark://spark-master:7077"            